"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { compressImage } from "@/lib/image";

export default function EditProfilePage(){
 const router=useRouter(); const [userId,setUserId]=useState(""); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [bio,setBio]=useState(""); const [location,setLocation]=useState(""); const [avatar,setAvatar]=useState(""); const [file,setFile]=useState<File|null>(null); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}setUserId(user.id);setEmail(user.email||"");const {data}=await s.from("profiles").select("full_name,email,avatar_url,bio,location_name").eq("id",user.id).maybeSingle();setName(data?.full_name||user.user_metadata?.full_name||"");setAvatar(data?.avatar_url||"");setBio(data?.bio||"");setLocation(data?.location_name||"");})()},[router]);
 async function save(){setSaving(true);setMessage("");try{const s=createClient();let avatarUrl=avatar;if(file){const compressed=await compressImage(file);const path=userId+"/avatar-"+Date.now()+".jpg";const up=await s.storage.from("profile-media").upload(path,compressed,{contentType:"image/jpeg",upsert:false});if(up.error)throw up.error;avatarUrl=s.storage.from("profile-media").getPublicUrl(path).data.publicUrl;}
 const p=await s.from("profiles").update({full_name:name.trim()||"SAVIS User",email:email.trim(),avatar_url:avatarUrl||null,bio:bio.trim()||null,location_name:location.trim()||null}).eq("id",userId);if(p.error)throw p.error;
 const {error:authError}=await s.auth.updateUser({email:email.trim(),data:{full_name:name.trim()}});if(authError)throw authError;
 setAvatar(avatarUrl);setFile(null);setMessage(email.trim()!==""?"Profile saved. If your email changed, Supabase may ask you to confirm the new address.":"Profile saved.");setTimeout(()=>router.push("/profile"),900);
 }catch(e){setMessage(e instanceof Error?e.message:"Could not save profile.");}finally{setSaving(false)}}
 return <main className="min-h-screen pb-20"><header className="sticky top-0 z-20 border-b border-white/10 savis-platinum px-4 py-3"><div className="mx-auto flex max-w-lg items-center justify-between"><Link href="/profile" className="text-sm font-bold text-[#B9C3C9]">← Profile</Link><b>Edit profile</b><span className="w-12"/></div></header><div className="mx-auto max-w-lg px-4 pt-6">
 <div className="mb-5 flex items-center gap-4"><div className="h-20 w-20 overflow-hidden rounded-full border border-white/10 bg-gradient-to-br from-[#6C0102] to-[#C7080C] flex items-center justify-center text-2xl font-black">{avatar?<img src={avatar} alt="" className="h-full w-full object-cover"/>:name.charAt(0).toUpperCase()||"U"}</div><label className="rounded-full border border-[#F5C451]/30 bg-[#F5C451]/10 px-4 py-2 text-xs font-black text-[#F5C451] cursor-pointer">Change photo<input type="file" accept="image/*" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div>
 <div className="space-y-4"><label className="block"><span className="text-xs font-bold text-[#B9C3C9]">Full name</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-2xl border border-white/10 bg-[#0b0c0e] px-4 py-3 outline-none"/></label><label className="block"><span className="text-xs font-bold text-[#B9C3C9]">Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-2xl border border-white/10 bg-[#0b0c0e] px-4 py-3 outline-none"/></label><label className="block"><span className="text-xs font-bold text-[#B9C3C9]">Bio</span><textarea value={bio} onChange={e=>setBio(e.target.value)} rows={4} className="mt-1 w-full rounded-2xl border border-white/10 bg-[#0b0c0e] px-4 py-3 outline-none" placeholder="Tell people a little about you"/></label><label className="block"><span className="text-xs font-bold text-[#B9C3C9]">Location</span><input value={location} onChange={e=>setLocation(e.target.value)} className="mt-1 w-full rounded-2xl border border-white/10 bg-[#0b0c0e] px-4 py-3 outline-none" placeholder="e.g. Westlands, Nairobi"/></label></div>
 {message&&<div className="mt-4 rounded-2xl border border-[#F5C451]/20 bg-[#F5C451]/5 p-3 text-xs text-[#F5C451]">{message}</div>}<button disabled={saving} onClick={()=>void save()} className="mt-5 w-full rounded-2xl bg-gradient-to-br from-[#E22227] to-[#C7080C] px-4 py-3 text-sm font-black disabled:opacity-50">{saving?"Saving…":"Save changes"}</button>
 </div></main>
}