"use client";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import Link from "next/link";
type Row={user_id:string;display_name:string|null;agent_code:string|null;active:boolean;notes:string|null;created_at:string};
export default function AgentManagement(){
 const db=useMemo(()=>createClient(),[]); const [ok,setOk]=useState<boolean|null>(null); const [rows,setRows]=useState<Row[]>([]); const [msg,setMsg]=useState("");
 async function load(){const {data}=await db.rpc("list_developer_agents");setRows((data||[]) as Row[]);}
 useEffect(()=>{void(async()=>{const {data:{user}}=await db.auth.getUser();if(!user){location.href="/login?next=/dev-console-9f3k/agents";return;}const {data}=await db.rpc("is_developer_admin");setOk(Boolean(data));if(data)await load();})();},[db]);
 async function toggle(row:Row){const {error}=await db.rpc("set_developer_agent_active",{p_user_id:row.user_id,p_active:!row.active});setMsg(error?error.message:"Agent status updated and audited.");if(!error)await load();}
 if(ok===null)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white">Checking developer access…</main>;
 if(!ok)return <main className="min-h-screen grid place-items-center bg-[#07050d] text-white">Developer access denied</main>;
 return <main className="min-h-screen bg-[#07050d] text-white"><header className="border-b border-violet-400/15 bg-[#0b0714]"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-5"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#F5C451]">Developer only</p><h1 className="text-2xl font-black">Agent Management</h1></div><Link href="/dev-console-9f3k" className="rounded-full border border-white/15 px-4 py-2 text-sm font-bold">← Console</Link></div></header><div className="mx-auto max-w-6xl px-4 py-6"><div className="rounded-3xl border border-amber-400/20 bg-amber-400/[.04] p-5"><p className="font-black text-amber-200">Separate developer-managed accounts</p><p className="mt-1 text-sm text-white/55">Only the developer allowlist can access this area. Status changes are audited.</p></div><section className="mt-5 rounded-3xl border border-white/10 bg-white/[.035] p-5"><h2 className="font-black">Registered accounts</h2><div className="mt-4 space-y-2">{rows.length===0?<p className="text-sm text-white/40">No managed accounts registered yet.</p>:rows.map(r=><div key={r.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/8 bg-black/15 p-4"><div><p className="font-black">{r.display_name||"Unnamed"}</p><p className="text-xs text-white/40">{r.agent_code||r.user_id}</p></div><button onClick={()=>void toggle(r)} className={`rounded-full px-4 py-2 text-xs font-black ${r.active?"bg-emerald-400/15 text-emerald-300":"bg-red-400/15 text-red-300"}`}>{r.active?"ACTIVE":"DISABLED"}</button></div>)}</div>{msg&&<p className="mt-4 text-sm text-white/55">{msg}</p>}</section></div></main>;
}